on: [push, pull_request]

jobs:
  check:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 1
    - uses: dtolnay/rust-toolchain@nightly
      with:
        components: rustfmt, clippy
    - run: cargo fmt -- --check
    - run: cargo clippy --all-targets -- --deny warnings
